### ISSUE TITLE
GL_VERSION string improperly parsed.

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [d-gamedev-team/gfm#102]
[The OpenGL reference for `glGetString`](https://www.opengl.org/sdk/docs/man4/html/glGetString.xhtml) states that a vendor specific suffix can follow the version number:

> Vendor-specific information may follow the version number. Its format depends on the implementation, but a space always separates the version number and the vendor-specific information.

However, GFM fails to parse such a version string, as it attempts to parse the vendor version as an integer:

    warning: Couldn't parse GL_VERSION string '3.0 Mesa 10.1.3', assuming OpenGL 1.1

The `getLimits` function in `opengl.d` should be altered to deal with the vendor version, for example by slicing off the resulting string up to the first space, or by using a regex. The documentation for `getVersionString` should also be updated.

**Comment by p0nce** [comment]
Good catch. I guess you stumbled upon it, let's see.

**Comment by p0nce** [comment]
Use tag 2.0.9+
Thanks for reporting.

**Comment by p0nce** [comment]
Reopened because of build breakage.

**Comment by p0nce** [comment]
Use 2.0.10+ instead.
