### ISSUE TITLE
Next breaking release (3.x.y) roadmap

### ISSUE THREAD

**Issue by p0nce** [d-gamedev-team/gfm#103]
- Either remove stuff in destructors or remove close functions. But we can't let non-trivial class destructors be called by the GC.

http://forum.dlang.org/post/mttziqysviupccuswzyn@forum.dlang.org

Class destructors are not permitted to allocate since called by the GC.
Class destructors are best leaved empty or like in Glamour, with a message to stderr that doesn't allocate.

(EDIT: ok, close functions are gone, GC destructors now trigger an error with informative message in debug mode)

~~- Either do not own Derelict.load calls, or allow to use a custom dynlib path. For SDL, allow to use a custom runtime version since DerelictSDL allows it.~~
~~- remove calls to .unload() for Derelict loaders, this might hide unreleased objects, but at least, it won't prevent to work with other libraries using derelict~~
~~- try to find a way to have scoped ownership for resources~~ (edit: found a way to fix the madness)

**Comment by p0nce** [comment]
Unfortunately would be a breaking change for anything that rely on GC behaviour to work now.

**Comment by p0nce** [comment]
We need an `bool isInGC() ` function

**Comment by p0nce** [comment]
Final solution for both classes and struct resources (now that a struct destructor could be called for the GC too).

In a `close()` function, if called by the GC, printf a warning and leak, else regular clean-up (RAII / Unique / scoped! was used).

**Comment by ZombineDev** [comment]
Since this will be a breaking release, you can switch to using `std.experimental.logger` from Phobos, instead of it being a DUB dependency.

**Comment by p0nce** [comment]
Not before a while, since std.experimental.logger only exist since DMDFE 2.067, and the latest GDC and LDC are still 2.066.

**Comment by ZombineDev** [comment]
Yep, only if LDC and GDC move to 2.067.

**Comment by p0nce** [comment]
- remove gfm.math.funcs.min and gfm.math.funcs.max

**Comment by p0nce** [comment]
db60dd1c512df7db4eb2c40d1ae57e644091c5e1
In GFM 3.x.y, actual resource clean-up will crash when called by the GC. This covers all cases and combinations.
`close()` methods will be removed in favor of `destroy` since what destructors will only ever do is call `close()`.
Destructors will be written in a way that support multiple calls.

**Comment by p0nce** [comment]
- Removed support for 2.065 frontends in gfm:math.
- New dependency: `imageformats`, replaces stb_image translation with shorter, more idiomatic code that is fixable. JPEG works again. https://github.com/lgvz/imageformats

**Comment by p0nce** [comment]
Version 3.0.0 is out.
Changelog added to the Wiki: https://github.com/d-gamedev-team/gfm/wiki/Changelog
