### ISSUE TITLE
Error in Matrix.orthographic() static method.

### ISSUE THREAD

**Issue by francesco-cattoglio** [d-gamedev-team/gfm#104]
I would do a proper pull request, but my repo is totally out of sync and it's just a 1-liner:
line 574, gfm/math/matrix.d:
 0, 0, 2 / dz, tz,

should be:

 0, 0, -2 / dz, tz,

As you can see from here: https://www.opengl.org/sdk/docs/man2/xhtml/glOrtho.xml
The z component has a really, really subtle minus in there!

**Comment by p0nce** [comment]
Thanks for the report.

You can update your fork by following this http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository

**Comment by p0nce** [comment]
Fixed, use v2.0.14 once it is update in the DUB registry.

`Still have to wait for 383 other packages to complete.`
