### ISSUE TITLE
FBO has no ability to change usage

### ISSUE THREAD

**Issue by drug007** [d-gamedev-team/gfm#119]
I implemented simple 3D picking example and I was forced to add this ability to gfm. The question is API to do it. Isn't `mode` more appropriate than `usage` here?

**Comment by p0nce** [comment]
Mode is indeed a better name than Usage.

However how about creating another FBO in READ mode and binding the same buffer to it?

**Comment by drug007** [comment]
Why another FBO if the first works very well? See [PR](https://github.com/d-gamedev-team/gfm/pull/120)
