### ISSUE TITLE
Why bool uniform should be set as int values?

### ISSUE THREAD

**Issue by drug007** [d-gamedev-team/gfm#123]
[Here](https://github.com/d-gamedev-team/gfm/blob/v2.3.26/opengl/gfm/opengl/uniform.d#L277) says that GL_BOOL is equal to int. It forces me do:
```
    bool my_uniform;
    ...
    program.uniform("my_uniform").set(cast(int)my_uniform);
```

**Comment by p0nce** [comment]
Looks like a bug indeed. I get back to you in ~10 hours.

**Comment by p0nce** [comment]
Use v2.3.27 or later.

**Comment by p0nce** [comment]
Wtf, I didn't fixed this.

**Comment by p0nce** [comment]
Sorry for the bad fix.
Use v2.3.28 or later.
