### ISSUE TITLE
Remove Dub dependencies on Logger

### ISSUE THREAD

**Issue by ColdenCullen** [d-gamedev-team/gfm#124]
Now that `std.experimental.logger` is part of Phobos, having it included through Dub is causing conflicts.

**Comment by p0nce** [comment]
The problem is that std.experimental.logger is only there for DMD 2.067.
So simply dropping the dependency would break gfm for LDC 0.15.1, GDC 4.9.2 and DMD 2.066 (this one I can drop without any hesitation, but the others I can't).

I need to think about how not to break DMDFE 2.066.

**Comment by p0nce** [comment]
I think I have a solution: dropping support for DMD 2.066, and only have the dependency with LDC and GDC compilers. It's possible through DUB suffixes.

**Comment by p0nce** [comment]
Hitting a DUB limitation there.

**Comment by ColdenCullen** [comment]
Ok, what if instead of removing dependencies, could you just wrap the imports in a `static if`? I can't remember what it is off the top of my head, but there's definitely a predefined thing for front end version.

**Comment by p0nce** [comment]
Yes you can use `static if` based on front-end version, but the import is exactly the same in both situations!

```
static if (front-end version > 2.066)
    import std.experimental.logger;
else
    import std.experimental.logger;
```

AFAIK you can't have conditional DUB directives based on front-end versions.

**Comment by ColdenCullen** [comment]
Lol duh, don't know why I didn't realize that. I think you're right about the DMD versions, I don't think Dub even has the concept of a compiler version. I think your compiler specific dependencies might be the way to go, assuming we can get that in.

**Comment by p0nce** [comment]
OK a solution was found.

Use gfm tag v2.3.30 or later.

But it was needed to change the module name of the older std.experimental.logger to std.historical.logger.
Two changes to do in Dash:
-  user code must now import it like in this commit: https://github.com/d-gamedev-team/gfm/commit/64322e8758a0fa10a2f6e342bd79e86b12ca1c1b

```d
static if( __VERSION__ >= 2067 )
    import std.experimental.logger;
else
    import std.historical.logger;
```
- change other `logger` dependencies to the new `v2.66.0` tag.

Such work-around can be thrown away later when 2.066 is behind us.

**Comment by p0nce** [comment]
I think it solves your problems.

**Comment by ColdenCullen** [comment]
Yup, thanks!
