### ISSUE TITLE
wideint improvements

### ISSUE THREAD

**Issue by p0nce** [d-gamedev-team/gfm#142]
http://forum.dlang.org/post/mailman.3383.1452120716.22025.digitalmars-d@puremagic.com

- [x] Better error message when user attempts to instantiate a wide int with
  non-power-of-2 bits. (Currently spews a whole bunch of internal
  compile errors.)
- [x] toString() needs to:
  1)  Be the non-allocating overload:

  	void toString(scope void delegate(const(char)[]) dg) {...}

  2) Output in decimal by default instead of hex.

- [x] Need a nice way of initializing wide ints from literals.

- [ ] Division performance can probably be improved. (OPTIONAL)

**Comment by quickfur** [comment]
For the first issue: https://github.com/d-gamedev-team/gfm/pull/143

**Comment by quickfur** [comment]
Attempt at implementing literals:  https://github.com/d-gamedev-team/gfm/pull/144

**Comment by quickfur** [comment]
For `toString`: https://github.com/d-gamedev-team/gfm/pull/145

**Comment by p0nce** [comment]
Nice, merge all 3. Available in GFM v3.0.9+

If you want to champion this and propose into Phobos, this is public domain and can be relicensed however you like.

**Comment by p0nce** [comment]
OK
