### ISSUE TITLE
ensureNotInGC will break with 2.071

### ISSUE THREAD

**Issue by p0nce** [d-gamedev-team/gfm#163]
Must use something else than `GC.free(1);`

**Comment by ZombineDev** [comment]
Yes it will stop working, however it may not be needed anymore:
https://github.com/D-Programming-Language/druntime/pull/1508/files#diff-6f1ab0423fff9dcd084ecf9a677dc426R3261

**Comment by ZombineDev** [comment]
This means that you can always free in the destructor, but if you do it while a GC collections is running it will be ignored.

**Comment by p0nce** [comment]
Yep, we'll switch to `GC.malloc` most probably, unless there is a way to tell if we are in a GC collection.

**Comment by p0nce** [comment]
Actually `ensureNotInGC` was still using `GC.malloc(1)` in GFM.
