### ISSUE TITLE
auto (or real) result for box distance functions?

### ISSUE THREAD

**Issue by denizzzka** [d-gamedev-team/gfm#167]
In my opinion, gfm.math.box: squaredDistance and distance should return an auto or real value instead of double

You will take appropriate patch from me?

**Comment by p0nce** [comment]
I would take a patch changing it into real, through I don't know what it changed speed-wise.

**Comment by denizzzka** [comment]
IMHO, speed will be same in both cases

**Comment by p0nce** [comment]
Available as v6.0.1
3de9196a01b2cf338027e1a8f9f16852bbfc3359
