### ISSUE TITLE
Online documentation is outdated by 4 versions (Was: No stb_image wrapper)

### ISSUE THREAD

**Issue by ahbaxter** [d-gamedev-team/gfm#171]
The readme speaks of an stb_image wrapper, but as far as I can tell this is incorrect. My guess is that this has been intentionally removed, just without thinking to remove the mention of it.

Edit: It was removed in e12066d3b72987effa3ab804358028d02ca2dc1e. Just the readme is at fault, then.

**Comment by p0nce** [comment]
Indeed, it was removed in version 3 in favor of the `imageformats` package. https://github.com/d-gamedev-team/gfm/wiki/Changelog

**Comment by p0nce** [comment]
I used bootdoc https://github.com/JakobOvrum/bootDoc, not sure what should be done instead (or keeping it?)
