### ISSUE TITLE
A lot of GFM class objects aren't exception-safe

### ISSUE THREAD

**Issue by p0nce** [d-gamedev-team/gfm#173]
See discussion in: https://github.com/d-gamedev-team/gfm/pull/172

It turns out if the constructor throw, the destructor is still called: https://dpaste.dzfl.pl/11ba07e0e6e5 (by the GC only?)
So we can't assume a valid resource in destructor.

**Comment by p0nce** [comment]
Doesn't happen with structs.

**Comment by Yoplitein** [comment]
Happens on scoped classes as well.

**Comment by p0nce** [comment]
I tend to think these days that if possible all D destructors should be callable multiple times.
- for classes, the constructor may have failed, and T.init should pass the destructor 
- for structs, no constructor may have been called, and T.init should pass the destructor

**Comment by p0nce** [comment]
Closed because reduced scope in GFM, wrappers are gone.
