### ISSUE TITLE
@fastmath

### ISSUE THREAD

**Issue by p0nce** [d-gamedev-team/gfm#184]
Breaking change. Everything should be marked @fastmath

**Comment by andrewbenton** [comment]
Does it need to be a breaking change?  I think we could version in a definition for `@fastmath` when it's not LDC.

**Comment by p0nce** [comment]
It is breaking change since adding it could change the results of FP operations.

**Comment by fastmath** [comment]
but it will be so fast

**Comment by p0nce** [comment]
True. In my test it does seem to make things faster, (unlike `-enable-cross-module-inlining` sadly) so it's planned. I have some audio algorithm that uses Vector so I will have to assess the impact. I assume it will be OK.
It is still a breaking change and will be a major tag.

**Comment by andrewbenton** [comment]
How do you feel about attaching it to the v7 issue then?

**Comment by p0nce** [comment]
Sure it will be done for v7

**Comment by p0nce** [comment]
Superseded by LDC providing fastmath as a commandline switch, as it should ;)
