### ISSUE TITLE
BUG: frustum contains method

### ISSUE THREAD

**Issue by peerhenry** [d-gamedev-team/gfm#191]
In the file "math/shapes.d", the method `contains(box3!T box)` for the Frustum struct contains a bug: The array for the eight corner vertices of the argument box are populated with only two distinct vectors. The bug is fixed by changing the three identical `i == 0` checks to to the proper index, ie: `i == 0`, `j == 0` and `k == 0` (from line 478 time of writing).

**Comment by p0nce** [comment]
Fixed in v6.2.13.
Thanks for noticing this :)
