### ISSUE TITLE
Ghosts of Vector.min and Vector.max

### ISSUE THREAD

**Issue by denizzzka** [d-gamedev-team/gfm#195]
```D
    static assert(std.traits.hasMember!(vec2d, "min"));
    static assert(std.traits.hasMember!(vec2d, "max"));
    static assert(std.traits.hasMember!(vec2d, "anythingElse"));
```
wtf?!

**Comment by p0nce** [comment]
Reproduced.

It's because it has `opDispatch`

```
import std.traits;

struct S
{  
    void opDispatch(string op)()
    {   
    }
}

static assert(std.traits.hasMember!(S, "whatever"));

void main()
{    
}
```

looks like hasMember does not check constraints of opDispatch.
Is it a problem for you?

**Comment by denizzzka** [comment]
> Is it a problem for you?

Yes.

I am try to detect "generic" 2D Boxes (by availability of "min" and "max" with rvalues of double vectors). But this issue is leads to false positive check of Vector's `min` and `max` for returning values.

**Comment by p0nce** [comment]
Use `__traits(compiles, x.min)`
