### ISSUE TITLE
Is module inteli.xmmintrin necessary?

### ISSUE THREAD

**Issue by ludo456** [d-gamedev-team/gfm#218]
In module gfm.math.funcs;
I have an 
`import inteli.xmmintrin;`

Edit: used by inverseSqrt hack. A bit tricky. Because of that, the lib depends on an Intel module? Maybe, a comment could be added.

**Comment by p0nce** [comment]
It's not absolutely necessary as is, but the goal was to add more SIMD such as in mat4 * vec4
And I'm making `intel-intrinsics` which is the only D lib that can reliably produce SIMD code, in all D compilers.
So I won't remove it.
